apiVersion: v1
kind: Service
metadata:
  labels:
    app: airprint
  name: airprint
  namespace: airprint
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32193
    port: 631
  selector:
    app: airprint
  type: LoadBalancer
